name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          
      - name: Export Java
        run: export JAVA_HOME=`/usr/libexec/java_home -v 1.8` && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Setup GitLab SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: gitlab.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY_GITLAB }}
          private-key-name: gitlab
          
      - name: Clone and Build Middle Backend
        run: git clone --single-branch --branch dev-master git@gitlab.com:piri/luna-middle-backend-api.git && cd luna-middle-backend-api && yarn && yarn build-prod
        
      - name: Clone Luna Mobile
        run: git clone --single-branch --branch dev-master git@gitlab.com:piri/luna-mobile.git && cd luna-mobile && yarn
        
        
      - name: Copy NodeJS Project
        run: rm -rf luna-mobile/apps/luna-tablet/nodejs-assets/nodejs-project && mv luna-middle-backend-api/build luna-mobile/apps/luna-tablet/nodejs-assets && mv luna-mobile/apps/luna-tablet/nodejs-assets/build luna-mobile/apps/luna-tablet/nodejs-assets/nodejs-project
        
      - name: Print File
        run:  ls luna-mobile/apps/luna-tablet/nodejs-assets/nodejs-project
        
      - name: Build Luna Tablet
        run: cd luna-mobile && yarn build:android-tablet:prod
        
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: "luna-tablet [${{ steps.time.outputs.time }}]"
          path: luna-mobile/apps/luna-tablet/android/app/build/outputs/apk/release/app-universal-release.apk
          
        
        
#       - name: LS
#         run: ls -la
