name: TEST
on:
 push:
  branches: [main]
 pull_request:
  branches: [main]
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  env:
   APP_PATH: luna-mobile/apps/luna-phone
   APP_TYPE: phone
   APP_ENV: dev
   TAG: LPD

  steps:

   - name: ADB
     run: echo $ANDROID_SDK_ROOT/tools/bin/sdkmanager --uninstall 'cmake;3.18.1'
   
   